name: Run application wow-auction-house-scraper
on:
  push:
    schedule:
      - cron: "0 8 * * *" # at 10:00 every day

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-18.04]
    timeout-minutes: 1380
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'schedule' || github.ref == 'refs/heads/master'}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - uses: actions/cache@v2
        with:
          path: /home/runner/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}

      - run: pip install -r requirements.txt
      - name: run main.py
        run: |
          python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLIZZARD_ACCESS_TOKEN: ${{ secrets.BLIZZARD_ACCESS_TOKEN }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: lassebenni/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
